name: "Secret Scan"
description: "Scan your repository for secrets"
author: "Max Schoening <max@max.wtf>"
inputs:
  include_path:  
    description: 'Path to configuration file with include path patterns'
    required: false
  exclude_path:  
    description: 'Path to configuration file with exclude path patterns'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.include_path }}
    - ${{ inputs.exclude_path }}
branding:
  icon: lock
  color: red
